"""Provider-neutral object storage interface (blueprint §17, ADR-0006, Scope §6.1).

``ObjectStorage`` is the only seam between the application and object storage.
Adapters implement it (S3, and later Azure/GCS); the in-memory fake lives in
``app.storage.fake``; the process-wide instance is selected from settings by
``app.storage.factory.get_storage``. No module outside ``app/storage/`` may
import a provider SDK — application code depends on this interface only.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from collections.abc import Buffer
from datetime import timedelta
from typing import Protocol, runtime_checkable

from app.storage.types import ObjectInfo, SignedUrl

DEFAULT_SIGNED_URL_TTL = timedelta(minutes=15)


@runtime_checkable
class WritableByteStream(Protocol):
    """The minimal write-only stream contract streaming consumers need.

    ``stream_object`` writes into anything implementing this (a secure
    temporary-file handle, a digest-computing wrapper, a test buffer), so the
    storage interface never depends on a concrete stream class and the AI
    layer can interpose digest/size bookkeeping around the write. The
    signature mirrors the standard library's ``BufferedWriter.write`` so every
    real binary stream satisfies it structurally.
    """

    def write(self, buffer: Buffer, /) -> int: ...


class ObjectStorage(ABC):
    """Minimal contract every storage provider adapter implements.

    Implementations keep buckets private, never expose public reads, and return
    only short-lived signed URLs. Object keys are always server-generated by
    the files module; adapters treat them as opaque strings.
    """

    @abstractmethod
    async def create_upload_url(
        self,
        *,
        file_id: uuid.UUID,
        object_key: str,
        content_type: str,
        size_bytes: int,
        expires_in: timedelta | None = None,
    ) -> SignedUrl:
        """Return a signed PUT URL the browser can upload to directly.

        ``file_id`` ties the signed URL to the file record for audit and
        provider-side tracing; ``content_type`` and ``size_bytes`` are the
        declared values validated before the URL is issued (blueprint §30).
        ``expires_in=None`` resolves to the adapter's configured default TTL.
        """

    @abstractmethod
    async def create_download_url(
        self,
        *,
        object_key: str,
        expires_in: timedelta | None = None,
    ) -> SignedUrl:
        """Return a short-lived signed GET URL for one object.

        ``expires_in=None`` resolves to the adapter's configured default TTL.
        """

    @abstractmethod
    async def head_object(self, object_key: str) -> ObjectInfo | None:
        """Return provider metadata for one object, or ``None`` when missing.

        Used by the upload-completion step to verify the browser really stored
        the object and that its size matches the declared size (Scope §6.3),
        and by the AI layer to validate a storage reference before reading it
        (v0.7 Scope §6.4).
        """

    @abstractmethod
    async def read_object(self, object_key: str, *, max_bytes: int | None = None) -> bytes:
        """Return one object's full bytes, read server-side.

        The AI layer uses this to resolve a private storage reference into a
        bounded in-memory :class:`~app.ai.attachments.Attachment` at the
        service/job boundary (v0.7 Scope §6.4, ADR-0017): bytes exist only in
        memory for one provider call and are never persisted, placed on the
        broker or logged. Raises :class:`KeyError` when the object does not
        exist; callers that care should ``head_object`` first so the AI
        resolver can translate the missing reference into its safe error.

        ``max_bytes`` caps the amount read *during the read itself*: when the
        object is larger the read raises :class:`ValueError` without pulling
        the whole body into memory, so a head/read race (the object grew or
        changed after ``head_object``) still fails bounded (Scope §6.4
        bounded-memory contract, §5.8).
        """

    @abstractmethod
    async def stream_object(
        self,
        object_key: str,
        *,
        destination: WritableByteStream,
        max_bytes: int | None = None,
    ) -> None:
        """Stream one object's body into an open writable binary stream, bounded.

        v0.8 Scope §2.3/§6.3: the non-inline transfer path never accumulates a
        large object in Python memory. The AI layer streams a verified private
        source into a secure temporary file through this seam, computing the
        SHA-256 digest incrementally and enforcing the byte ceiling during the
        read, so a 50 MB source is never held in memory or embedded in JSON.

        The adapter must not read more than ``max_bytes`` bytes from the
        provider: a larger body raises :class:`ValueError` mid-stream without
        buffering the remainder, mirroring :meth:`read_object`'s bounded read
        so a head/read race still fails bounded. Raises :class:`KeyError` when
        the object does not exist. The stream is closed even on failure, so
        repeated AI transfers never leak provider connections.
        """

    @abstractmethod
    async def delete_object(self, object_key: str) -> None:
        """Permanently remove one object from the provider; idempotent."""

    @abstractmethod
    async def list_objects(
        self,
        prefix: str,
        *,
        limit: int = 1000,
        start_after: str | None = None,
    ) -> list[ObjectInfo]:
        """Return up to ``limit`` objects whose key starts with ``prefix``.

        The AI retention job uses this to sweep orphaned analyse-only objects
        from the organisation-scoped AI scratch namespace (v0.7 Scope §6.5):
        listed metadata carries the provider's ``last_modified`` so the sweep
        can age them out without storing a registry of scratch keys. The
        result is bounded by ``limit`` and pages with ``start_after`` — the
        exclusive lexicographic marker of the last key the caller already
        processed — so the caller can sweep a namespace of any size one page
        at a time without re-reading fresh objects forever. Keys stay opaque
        strings.
        """

    @abstractmethod
    async def ensure_bucket(self) -> None:
        """Create the configured bucket when missing (lazy, idempotent)."""
