"""Provider-neutral object storage interface (blueprint §17, ADR-0006, Scope §6.1).

``ObjectStorage`` is the only seam between the application and object storage.
Adapters implement it (S3, and later Azure/GCS); the in-memory fake lives in
``app.storage.fake``; the process-wide instance is selected from settings by
``app.storage.factory.get_storage``. No module outside ``app/storage/`` may
import a provider SDK — application code depends on this interface only.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from datetime import timedelta

from app.storage.types import ObjectInfo, SignedUrl

DEFAULT_SIGNED_URL_TTL = timedelta(minutes=15)


class ObjectStorage(ABC):
    """Minimal contract every storage provider adapter implements.

    Implementations keep buckets private, never expose public reads, and return
    only short-lived signed URLs. Object keys are always server-generated by
    the files module; adapters treat them as opaque strings.
    """

    @abstractmethod
    async def create_upload_url(
        self,
        *,
        file_id: uuid.UUID,
        object_key: str,
        content_type: str,
        size_bytes: int,
        expires_in: timedelta | None = None,
    ) -> SignedUrl:
        """Return a signed PUT URL the browser can upload to directly.

        ``file_id`` ties the signed URL to the file record for audit and
        provider-side tracing; ``content_type`` and ``size_bytes`` are the
        declared values validated before the URL is issued (blueprint §30).
        ``expires_in=None`` resolves to the adapter's configured default TTL.
        """

    @abstractmethod
    async def create_download_url(
        self,
        *,
        object_key: str,
        expires_in: timedelta | None = None,
    ) -> SignedUrl:
        """Return a short-lived signed GET URL for one object.

        ``expires_in=None`` resolves to the adapter's configured default TTL.
        """

    @abstractmethod
    async def head_object(self, object_key: str) -> ObjectInfo | None:
        """Return provider metadata for one object, or ``None`` when missing.

        Used by the upload-completion step to verify the browser really stored
        the object and that its size matches the declared size (Scope §6.3).
        """

    @abstractmethod
    async def delete_object(self, object_key: str) -> None:
        """Permanently remove one object from the provider; idempotent."""

    @abstractmethod
    async def ensure_bucket(self) -> None:
        """Create the configured bucket when missing (lazy, idempotent)."""
